services:
  # 1. PostgreSQL bazasi
  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2103
      - POSTGRES_DB=logistika_db
      - TZ=Asia/Tashkent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d logistika_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Redis server
  logistika-redis:
    image: redis:7-alpine
    container_name: logistika-redis
    restart: always
    ports:
      - "6380:6379"  # Tashqi portni 6380 qildik, shunda Mac-dagi eski Redis bilan urishmaydi!
    volumes:
      - redis_data:/data

  # 3. OSRM Router (Xarita serveri)
  osrm:
    image: osrm/osrm-backend
    container_name: osrm_router
    platform: linux/amd64        # Apple Silicon Mac-lar uchun majburiy
    volumes:
      - .:/data
    ports:
      - "5001:5000"              # Tashqi portni 5001 qildik, AirPlay bilan urishmaydi!
    command: osrm-routed --algorithm mld /data/uzbekistan-260710.osm.pbf
    restart: always

  # 4. FastAPI Web dasturi
  web:
    build: .
    container_name: fastapi_web_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
      - FORCE_COLOR=1
    command:
      - uvicorn
      - config.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
    restart: always
    depends_on:
      db:
        condition: service_healthy
      logistika-redis:
        condition: service_started
      osrm:
        condition: service_started

  # 5. Telegram Bot
  bot:
    build: .
    container_name: aiogram_telegram_bot
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
    command: python main.py
    restart: always
    depends_on:
      db:
        condition: service_healthy
      logistika-redis:
        condition: service_started
      osrm:
        condition: service_started

# Barcha volume'lar bitta joyda jamlandi
volumes:
  postgres_data:
  redis_data: