"""add_total_km_to_drivers

Revision ID: 8a3209d29df7
Revises: 78fe0426e4da
Create Date: 2026-06-04 16:20:05.560381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a3209d29df7'
down_revision: Union[str, Sequence[str], None] = '78fe0426e4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_ai_usage_user_date')
    )
    op.create_index(op.f('ix_ai_usage_usage_date'), 'ai_usage', ['usage_date'], unique=False)
    op.create_index(op.f('ix_ai_usage_user_id'), 'ai_usage', ['user_id'], unique=False)
    op.create_table('user_tariff_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('tariff_code', sa.String(length=64), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_tariff_payments_user_billing_month', 'user_tariff_payments', ['user_id', 'billing_month'], unique=False)
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text("now() + interval '2 minutes'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('driver_documents')
    op.drop_index('ix_email_otps_email', table_name='email_otps')
    op.drop_table('email_otps')
    op.alter_column('ai_commands', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('chats', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.add_column('drivers', sa.Column('total_km', sa.Integer(), nullable=False))
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_constraint('order_offers_truck_id_fkey', 'order_offers', type_='foreignkey')
    op.drop_column('order_offers', 'driver_longitude')
    op.drop_column('order_offers', 'truck_id')
    op.drop_column('order_offers', 'counter_price')
    op.drop_column('order_offers', 'driver_completed_orders_snapshot')
    op.drop_column('order_offers', 'driver_latitude')
    op.drop_column('order_offers', 'counter_at')
    op.drop_column('order_offers', 'driver_rating_snapshot')
    op.drop_column('order_offers', 'counter_comment')
    op.drop_index('ix_order_waypoints_city', table_name='order_waypoints')
    op.drop_column('order_waypoints', 'city')
    op.alter_column('ratings', 'rated_by_user',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('ratings', 'target_user',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'target_user',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('ratings', 'rated_by_user',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('order_waypoints', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index('ix_order_waypoints_city', 'order_waypoints', ['city'], unique=False)
    op.add_column('order_offers', sa.Column('counter_comment', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('order_offers', sa.Column('driver_rating_snapshot', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('order_offers', sa.Column('counter_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order_offers', sa.Column('driver_latitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.add_column('order_offers', sa.Column('driver_completed_orders_snapshot', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('order_offers', sa.Column('counter_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('order_offers', sa.Column('truck_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order_offers', sa.Column('driver_longitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.create_foreign_key('order_offers_truck_id_fkey', 'order_offers', 'truck_types', ['truck_id'], ['id'])
    op.alter_column('messages', 'sender_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('drivers', 'total_km')
    op.alter_column('chats', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('ai_commands', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('email_otps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('hashed_pw', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='email_otps_pkey')
    )
    op.create_index('ix_email_otps_email', 'email_otps', ['email'], unique=False)
    op.create_table('driver_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doc_type', postgresql.ENUM('DRIVER_LICENSE', 'PASSPORT', 'TRUCK_TECH_PASS', 'TRUCK_INSURANCE', 'MEDICAL_CERT', 'OTHER', name='documenttype'), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_expired', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('verification_status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='driververificationstatus'), autoincrement=False, nullable=False),
    sa.Column('rejection_reason', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name='driver_documents_driver_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name='driver_documents_verified_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='driver_documents_pkey')
    )
    op.drop_table('order_tracks')
    op.drop_table('verification_codes')
    op.drop_index('ix_user_tariff_payments_user_billing_month', table_name='user_tariff_payments')
    op.drop_table('user_tariff_payments')
    op.drop_index(op.f('ix_ai_usage_user_id'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_usage_date'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
