"""added token columns

Revision ID: 94e7e7adb95b
Revises: 5b9b335018c1
Create Date: 2026-04-14 14:30:19.471154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e7e7adb95b'
down_revision: Union[str, Sequence[str], None] = '5b9b335018c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_expires')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
