"""unified_chats_model_update

Revision ID: adb6c9f7feac
Revises: 1179eea8a15e
Create Date: 2026-06-11 19:05:26.704030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb6c9f7feac'
down_revision: Union[str, Sequence[str], None] = '1179eea8a15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'chats', ['chat_id'], ['id'])
    
    # Migrate existing data
    op.execute("UPDATE orders SET chat_id = chats.id FROM chats WHERE chats.order_id = orders.id")
    
    op.drop_constraint('chats_order_id_key', 'chats', type_='unique')
    op.drop_constraint('chats_order_id_fkey', 'chats', type_='foreignkey')
    op.drop_column('chats', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'chat_id')
    op.add_column('chats', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chats_order_id_fkey', 'chats', 'orders', ['order_id'], ['id'])
    op.create_unique_constraint('chats_order_id_key', 'chats', ['order_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
