"""start

Revision ID: c0585cf96999
Revises: 
Create Date: 2026-04-24 16:12:55.662742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0585cf96999'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('truck_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('max_weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_volume', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('length', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('width', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pallet_capacity', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'sender', 'driver', 'guest', name='userrole'), server_default='guest', nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('truck_type_id', sa.Integer(), nullable=False),
    sa.Column('truck_number', sa.String(length=20), nullable=False),
    sa.Column('capacity_ton', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('capacity_m3', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('current_city', sa.String(length=300), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_trips', sa.Integer(), nullable=False),
    sa.Column('docs_verified', sa.Boolean(), nullable=False),
    sa.Column('is_live_location_active', sa.Boolean(), nullable=False),
    sa.Column('live_location_expires', sa.DateTime(), nullable=True),
    sa.Column('last_latitude', sa.Float(), nullable=True),
    sa.Column('last_longitude', sa.Float(), nullable=True),
    sa.Column('last_location_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['truck_type_id'], ['truck_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('truck_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_drivers_current_city'), 'drivers', ['current_city'], unique=False)
    op.create_table('driver_announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('from_city', sa.String(), nullable=False),
    sa.Column('to_city', sa.String(), nullable=False),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_announcements_from_city'), 'driver_announcements', ['from_city'], unique=False)
    op.create_index(op.f('ix_driver_announcements_to_city'), 'driver_announcements', ['to_city'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('cargo_name', sa.String(length=200), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('volume', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('from_city', sa.String(), nullable=False),
    sa.Column('to_city', sa.String(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('required_truck_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pickup_date', sa.DateTime(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['required_truck_type_id'], ['truck_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_from_city'), 'orders', ['from_city'], unique=False)
    op.create_index(op.f('ix_orders_to_city'), 'orders', ['to_city'], unique=False)
    op.create_table('announcement_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('cargo_description', sa.String(length=500), nullable=False),
    sa.Column('offered_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='announcementofferstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['driver_announcements.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('offered_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='offerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_offers')
    op.drop_table('announcement_offers')
    op.drop_index(op.f('ix_orders_to_city'), table_name='orders')
    op.drop_index(op.f('ix_orders_from_city'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_driver_announcements_to_city'), table_name='driver_announcements')
    op.drop_index(op.f('ix_driver_announcements_from_city'), table_name='driver_announcements')
    op.drop_table('driver_announcements')
    op.drop_index(op.f('ix_drivers_current_city'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_table('users')
    op.drop_table('truck_types')
    # ### end Alembic commands ###
