"""set_server_default_for_timestamps

Revision ID: d5f9d6ed31d1
Revises: 8a3209d29df7
Create Date: 2026-06-05 16:07:42.421629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f9d6ed31d1'
down_revision: Union[str, Sequence[str], None] = '8a3209d29df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
